name: Test
on: push
jobs:
  test:
    name: Test
    strategy:
      matrix:
        python: [3.9, 3.11, 3.12]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: v1/${{ runner.os }}/pypi-${{matrix.python}}/${{ hashFiles('{requirements,development}.txt') }}
          restore-keys: v1/${{ runner.os }}/pypi-${matrix.python}/
      - run: make test
