name: Test
on: push
jobs:
  test:
    name: Test
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: v1/${{ runner.os }}/pypi-${{matrix.python}}/${{ hashFiles('{requirements,development}.txt') }}
          restore-keys: v1/${{ runner.os }}/pypi-${matrix.python}/
      - run: make test
